version: '3.7'
services:
  consul:
    image: hashicorp/consul:latest
    container_name: consul
    ports:
      - "8500:8500"
    command: "agent -dev -client=0.0.0.0"
    healthcheck:
      test: ["CMD", "consul", "members"]
      interval: 5s
      timeout: 2s
      retries: 5
  booking-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - consul
    environment:
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500